# Generated by Django 3.0.5 on 2020-04-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_pround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pround',
            field=models.ImageField(upload_to=''),
        ),
    ]
