# Generated by Django 3.0.5 on 2020-04-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200407_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pround',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
